app/informacion/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from app.informacion.views import *


urlpatterns = [
	url(r'^datos_generales/nuevo/$', DatosGeneral_crear, name='datos_generales_crear'),
	url(r'^datos_generales/listar/', DatosGeneralesList.as_view(),name='datos_generales_listar'),
	url(r'^datos_generales/consultar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/$', DatosGenerales_consultar,name='datos_generales_consultar'),
	url(r'^datos_generales/editar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/$', DatosGenerales_edit,name='datos_generales_editar'),

	url(r'^fichas/nuevo/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/$', Fichas_crear, name='fichas_crear'),
	url(r'^fichas/listar/', FichasList.as_view(),name='fichas_listar'),


	url(r'^estado_general/nuevo/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/(?P<num>\d+)/$', EstadoGeneral_crear, name='estado_general_crear'),
	url(r'^estado_general/listar', EstadoGeneralList.as_view(),name='estado_general_listar'),
	url(r'^estado_general/editar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/(?P<num>\d+)/$', EstadoGeneral_edit,name='estado_general_editar'),
	url(r'^estado_general/consultar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/(?P<num>\d+)/$', EstadoGeneral_consultar,name='estado_general_consultar'),




]

orto/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app.home.views import index
# -*- coding: utf-8 -*-

urlpatterns = [
	url(r'^$', index), 
    url(r'^admin/', admin.site.urls),
    url(r'^informacion/', include ('app.informacion.urls',namespace="informacion")),
]

templates/base/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
<head>
	<meta charset="UTF-8">

	<link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
		<script src="https://code.jquery.com/jquery-1.10.2.min.js"></script>
	<script src="{% static 'js/bootstrap.min.js' %}"></script>
	<link rel="stylesheet" href="http://code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css"> 
	<script src="http://code.jquery.com/ui/1.11.0/jquery-ui.js"></script>

	<style type="text/css"> 
		.dropdown-toggle{
		 display:block;
		  width: 9em;
		  word-wrap: break-word;
		} 
	</style>

	<title>{% block title %} Base {% endblock %}</title>
</head>
<body>

<div class="container">

	{% block navbar %}
		<div class="bs-docs-section clearfix">
		    <div class="row">
		        <div class="col-lg-12">
		            <div class="bs-component">
		            	<nav class="navbar navbar-default">
		                	<div class="container-fluid">
		                  		<div class="navbar-header">
		                    		<a class="navbar-brand" href="#">SOUES</a>
		                  		</div>
		                  	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
		                    	<ul class="nav navbar-nav">
		                      		<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Informacion General<span class="caret"></span></a>
				                        <ul class="dropdown-menu" role="menu">
				                        	<li><a href="{% url 'informacion:datos_generales_crear' %}">Datos Generales</a></li>
				                        	<li><a href="">Estado General</a></li>
				                        </ul>
		                      		</li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Tipo de Perfil<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href=" # "></a></li>
				                          	<li><a href=" # "></a></li>
			                        	</ul>
			                        </li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Aspectos de Dentici&oacuten<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href=" # "></a></li>
				                          	<li><a href=" # "></a></li>
			                        	</ul>
			                        </li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">An&aacutelisis Radiografico<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href=" # "></a></li>
				                          	<li><a href=" # "></a></li>
			                        	</ul>
			                        </li>
			                        <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">An&aacutelisis Cefalom&eacutetrico<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href=" # "></a></li>
				                          	<li><a href=" # "></a></li>
			                        	</ul>
			                        </li>
			                         <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">An&aacutelisis de Dentici&oacuten<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href=" # "></a></li>
				                          	<li><a href=" # "></a></li>
			                        	</ul>
			                        </li>
			                         <li class="dropdown">
			                        	<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Diagnostico Ortodontico General<span class="caret"></span></a>
			                        	<ul class="dropdown-menu" role="menu">
				                          	<li><a href=" # "></a></li>
				                          	<li><a href=" # "></a></li>
			                        	</ul>
			                        </li>
		                    	</ul>
		                    	<!-- <ul class="nav navbar-nav navbar-right">
		                        	<li class="dropdown">
		                        		<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Opciones<span class="caret"></span></a>
		                        		<ul class="dropdown-menu" role="menu">
		                          			<li><a href="#">Salir</a></li>
		                        		</ul> -->
		                      		</li>
		                    	</ul>
		                    </div>
		                </div>
		            </nav>
		        </div>
           	</div>
        </div>
    </div>   
    <div>
    {% endblock %} 

	{% block header %}
	<h4>Este es el bloque del header base </h4>
	{% endblock %}

	{% block content %}
	<h5>Este es el contenido del archivo base</h5>
	{% endblock %}

	{% block tabla %}
	{% endblock %}	

	


	</div>
	
</body>
</html>