app/informacion/urls.py
from django.conf.urls import url,include
from django.contrib import admin

from app.informacion.views import *


urlpatterns = [
	url(r'^datos_generales/nuevo/$', DatosGeneral_crear, name='datos_generales_crear'),
	url(r'^datos_generales/listar/', DatosGeneralesList.as_view(),name='datos_generales_listar'),
	url(r'^datos_generales/consultar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/$', DatosGenerales_consultar,name='datos_generales_consultar'),
	url(r'^datos_generales/editar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/$', DatosGenerales_edit,name='datos_generales_editar'),

	url(r'^fichas/nuevo/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/$', Fichas_crear, name='fichas_crear'),
	url(r'^fichas/listar/', FichasList.as_view(),name='fichas_listar'),


	url(r'^estado_general/nuevo/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/(?P<num>\d+)/$', EstadoGeneral_crear, name='estado_general_crear'),
	url(r'^estado_general/listar', EstadoGeneralList.as_view(),name='estado_general_listar'),
	url(r'^estado_general/editar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/(?P<num>\d+)/$', EstadoGeneral_edit,name='estado_general_editar'),
	url(r'^estado_general/consultar/(?P<codi>[0-9]{4}(.).*?((?:[a-z][a-z0-9_]*)?))/(?P<num>\d+)/$', EstadoGeneral_consultar,name='estado_general_consultar'),




]

orto/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from app.home.views import index
# -*- coding: utf-8 -*-

urlpatterns = [
	url(r'^$', index), 
    url(r'^admin/', admin.site.urls),
    url(r'^informacion/', include ('app.informacion.urls',namespace="informacion")),
]

templates/estado_general/form.html
{% extends 'base/base.html' %}

{% block title %}
	Estado_general
{% endblock %}
{% block header %}
{% endblock %}

{% block content %}
<form method="POST">
	{% csrf_token %}
	
	<div class="row">
		<div class="col-md-8 col-md-offset-2">
			<div class="form-group">
				{{form.fichas}}
			</div>
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">
			<label for="{{form.cambio_salud.name}}">{{form.cambio_salud.label}}</label>	
			{{form.cambio_salud}}
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">
		
			<label for="{{form.detalle_enf_operacion.name}}">{{form.detalle_enf_operacion.label}}</label>
			<input type="checkbox" onclick="var input = document.getElementById('{{form.detalle_enf_operacion.id_for_label}}'); if(this.checked){ input.disabled = false; input.focus();}else{input.disabled=true;}" />	
			{{form.detalle_enf_operacion}}
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">
			<label for="{{form.otras_enfermedades.name}}">{{form.otras_enfermedades.label}}</label>	
			{{form.otras_enfermedades}}
		</div>
	</div>
	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">
			<label for="{{form.detalle_otra_enfermedad.name}}">{{form.detalle_otra_enfermedad.label}}</label>	
			{{form.detalle_otra_enfermedad}}
		</div>
	</div>

	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">

			<label for="{{form.detalle_medicamento.name}}">{{form.detalle_medicamento.label}}</label>	
			<input type="checkbox" onclick="var input = document.getElementById('{{form.detalle_medicamento.id_for_label}}'); if(this.checked){ input.disabled = false; input.focus();}else{input.disabled=true;}" />
			{{form.detalle_medicamento}}
				
		</div>
	</div>

	<div class="col-md-8 col-md-offset-2">
		<div class="form-group">
			<button type="submit" class="btn btn-success">Guardar</button>
			<button type="button" onclick=" location.href='{% url 'informacion:estado_general_listar' %}'"" class="btn btn-warning">Cancelar</button>
		</div>
	</div>
</form>

	
{% endblock %}